after-startup-command = [
  'exec-and-forget sketchybar',
]

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'

[gaps]
inner.horizontal = 14
inner.vertical =   14
outer.top = [{ monitor."Built-in" = 0 }, 0]
outer.bottom = [{ monitor."Built-in" = 32 }, 32]
outer.left =       0
outer.right =      0

[mode.main.binding]
alt-i = 'workspace Infra' # Infra (DevOps)
alt-d = 'workspace Dev' # Dev (IDE, Coding Tools, etc)
alt-t = 'workspace Terminal' # Terminal (Main Terminal For Coding with web window inside)
alt-w = 'workspace Web' # Web (Browse or any web development related like figma, etc)
alt-c = 'workspace Chat' # Chat (Chat related apps like Slack, Teams, Whatsapp etc)
alt-r = 'workspace Reading' # Reading Including book, notes (Kindle, Inkdrop)
alt-p = 'workspace Planing' # planing emails (Linear, Jira, Spark etc..)
alt-a = 'workspace Any' # Any (Social Media, Spotify, Music etc)
alt-1 = 'workspace External-1' # Workspace for external monitor more focus on coding and devops
alt-2 = 'workspace External-2' # Workspace for external monitor more focusing on reading and browsing

alt-shift-i = ['move-node-to-workspace Infra', 'workspace Infra']
alt-shift-d = ['move-node-to-workspace Dev', 'workspace Dev']
alt-shift-t = ['move-node-to-workspace Terminal', 'workspace Terminal']
alt-shift-w = ['move-node-to-workspace Web', 'workspace Web']
alt-shift-c = ['move-node-to-workspace Chat', 'workspace Chat']
alt-shift-r = ['move-node-to-workspace Reading', 'workspace Reading']
alt-shift-p = ['move-node-to-workspace Planing', 'workspace Planing']
alt-shift-a = ['move-node-to-workspace Any', 'workspace Any']
alt-shift-1 = ['move-node-to-workspace External-1', 'workspace External-1']
alt-shift-2 = ['move-node-to-workspace External-2', 'workspace External-2']

alt-shift-h = 'move left'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
alt-shift-j = 'move down'

alt-tab = 'focus-back-and-forth'

# Let 'focus' work when all windows are floating
alt-h = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace left || $HOME/.config/aerospace/scripts/focus-window.sh left'
alt-j = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace down || $HOME/.config/aerospace/scripts/focus-window.sh down'
alt-k = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace up || $HOME/.config/aerospace/scripts/focus-window.sh up'
alt-l = 'exec-and-forget aerospace focus --boundaries-action wrap-around-the-workspace right || $HOME/.config/aerospace/scripts/focus-window.sh right'

alt-f = 'layout accordion tiles'
alt-slash= 'layout horizontal vertical'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-0 = 'flatten-workspace-tree'

alt-shift-f = 'layout floating tiling'
alt-ctrl-shift-y = 'reload-config'

# Workspace Infra
[[on-window-detected]]
if.app-id = 'com.mongodb.compass'
run = ['layout floating', 'move-node-to-workspace Infra']

[[on-window-detected]]
if.app-id = 'com.jetbrains.datagrip'
run = ['layout floating', 'move-node-to-workspace Infra']

[[on-window-detected]]
if.app-id = 'com.electron.kontena-lens'
run = ['layout floating', 'move-node-to-workspace Infra']

# Workspace Dev
[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'app.yaak.desktop'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.jgraph.drawio.desktop'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.conductor.app'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.install4j.9806-1938-4586-6531.70'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.usebruno.app'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'dev.kdrag0n.MacVirt'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'ai.elementlabs.lmstudio'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'org.wireshark.Wireshark'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.axosoft.gitkraken'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'io.httpie.desktop'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.exafunction.windsurf'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'tonyapp.devutils'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = ['layout floating', 'move-node-to-workspace Dev']

[[on-window-detected]]
if.app-id = 'com.anthropic.claudefordesktop'
run = ['layout floating', 'move-node-to-workspace Dev']

# Workspace Terminal
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['move-node-to-workspace Terminal']

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['move-node-to-workspace Terminal']

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = ['move-node-to-workspace Terminal']

# Workspace Web
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = ['move-node-to-workspace Web']

[[on-window-detected]]
if.app-id = 'company.thebrowser.dia'
run = ['layout floating', 'move-node-to-workspace Web']

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = ['layout floating', 'move-node-to-workspace Web']

# Workspace Reading
[[on-window-detected]]
if.app-id = 'com.kingsoft.wpsoffice.mac.global'
run = ['layout floating', 'move-node-to-workspace Reading']

[[on-window-detected]]
if.app-id = 'com.amazon.Lassen'
run = ['layout floating', 'move-node-to-workspace Reading']

# Workspace Plan
[[on-window-detected]]
if.app-id = 'com.readdle.SparkDesktop.appstore'
run = ['layout floating', 'move-node-to-workspace Planing']

[[on-window-detected]]
if.app-id = 'info.pkpk.inkdrop'
run = ['layout floating', 'move-node-to-workspace Planing']

[[on-window-detected]]
if.app-id = 'com.linear'
run = ['layout floating', 'move-node-to-workspace Planing']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['layout floating', 'move-node-to-workspace Planing']

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = ['layout floating', 'move-node-to-workspace Planing']

# Workspace Chat
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout floating', 'move-node-to-workspace Chat']

[[on-window-detected]]
if.app-id = 'app.legcord.Legcord'
run = ['layout floating', 'move-node-to-workspace Chat']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['layout floating', 'move-node-to-workspace Chat']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout floating', 'move-node-to-workspace Chat']

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout floating', 'move-node-to-workspace Chat']

# Workspace Any
[[on-window-detected]]
if.app-id = 'com.facebook.archon'
run = ['layout floating', 'move-node-to-workspace Any']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout floating', 'move-node-to-workspace Any']

[[on-window-detected]]
if.app-id = 'com.apple.TV'
run = ['layout floating', 'move-node-to-workspace Any']

[workspace-to-monitor-force-assignment]
Infra = '^built-in'
Dev = '^built-in'
Terminal = '^built-in'
Web = '^built-in'
Chat = '^built-in'
Reading = '^built-in'
Planing = '^built-in'
Any = '^built-in'
External-1 = 1
External-2 = 1
