format = """\
[](fg:arrow)\
$username\
$os\
(\
    at \
    $directory\
)\
(\
    via \
    $python\
    $golang\
    $nodejs\
    $c\
    $rust\
    $terraform\
    $java\
    $character\
)\
"""

right_format = """\
$git_branch\
$git_status\
$cmd_duration\
$docker_context\
$kubernetes\
$time \
"""

# Add the modules you need

# Disable the blank line at the start of the prompt
add_newline = true


# I disabled some modules (Rust, Java...) since some things aren't installed in my machine, enable them if you need.

[username]
format = '[îƒ ](fg:red) '
disabled = true
show_always = false

[os]
format = "[$symbol]($style fg:cyan) "
disabled = false

[os.symbols]
Alpine = "ïŒ€ "
Arch = "ïŒƒ "
Debian = "ïŒ† "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
Linux = "ïŒš "
Manjaro = "ïŒ’ "
Mint = "ïŒ "
NixOS = "ï†— "
Macos = "ïŒ“ "
openSUSE = "ïŒ” "
Pop = "îŠ£ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Windows = "ï…º "

[character]
disabled = false
success_symbol = '[ï²](bold fg:green)'
error_symbol = '[ï²](bold fg:red)'
vimcmd_symbol = '[â–³](bold fg:green)'

[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true
read_only =" î©µ "

[cmd_duration]
disabled = false
format = "took [ï“£ $duration]($style) "
min_time = 500

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "îœ‚ "

[git_status]
format = '[ $all_status$ahead_behind ]($style)'
disabled = true

[docker_context]
disabled=false
symbol = "ïŒˆ "

[kubernetes]
disabled=false
symbol = "î  "
format = "[$symbol$context]($style) "

[time]
disabled = false
format = "[$time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[package]
disabled=true

[fill]
symbol = " "

[nodejs]
format = "[$symbol$version ]($style)"
symbol = "îœ˜ "
version_format = "${raw}"
disabled=false

[python]
disabled=false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
symbol = "î˜† "
version_format = "${raw}"

[java]
format = "[$symbol$version ]($style)"
version_format = "${raw}"
symbol = "î™­ "
disabled = true

[c]
format = "[$symbol($version(-$name)) ]($style)"
symbol = "î˜ "
version_format = "${raw}"
disabled=true

[golang]
symbol = "î˜§"
format = '[$symbol( $version) ]($style)'

[rust]
format ="[$symbol$version ]($style)"
symbol = "îš‹ "
version_format = "${raw}"

[terraform]
format = "[$symbol($version) ]($style)"
symbol = "ğŸ "
version_format = "${raw}"
disabled=false
