[env]
TERM = "xterm-256color"

[font]
size = 13

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
option_as_alt = "Both"
decorations = "none"
decorations_theme_variant = "none"
padding = { x = 0, y = 0  }
dimensions = { columns = 210, lines = 60 }
dynamic_padding = true
startup_mode = "Windowed"
title = "DevTerm"
dynamic_title=false
opacity = 1
blur = false

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" }
]

[cursor.style]
shape = "Block"

[general]
live_config_reload = true
working_directory = "None"

import = [
  "~/.dotfiles/terminals/alacritty/theme.toml",
]
