live_config_reload = true
working_directory = "None"

import = [
  "~/.dotfiles/terminals/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 12

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
option_as_alt = "Both"
decorations = "buttonless"
padding = { x = 0, y = 0  }
dimensions = { columns = 200, lines = 55 }
dynamic_padding = false
startup_mode = "Windowed"
title = "DevTerm"
dynamic_title=false

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" }
]

[cursor.style]
shape = "Block"

[cursor]
unfocused_hollow = false
